env:
  - CGO_CFLAGS={{.Env.CGO_CFLAGS}}
  - CGO_LDFLAGS={{.Env.CGO_LDFLAGS}}
before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -w -s -X main.version={{.Version}}
    main: ./cmd/bouheki
    binary: bouheki
archives:
  - replacements:
      linux: Linux
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
